//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIMED {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GIMED.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code already exists.
        /// </summary>
        internal static string MsgCodeExists {
            get {
                return ResourceManager.GetString("MsgCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions for access and use-general not found.
        /// </summary>
        internal static string MsgCondAccessAndUseNotFound {
            get {
                return ResourceManager.GetString("MsgCondAccessAndUseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance already exists.
        /// </summary>
        internal static string MsgDistanceAlreadyExists {
            get {
                return ResourceManager.GetString("MsgDistanceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance cannot be negative or zero.
        /// </summary>
        internal static string MsgDistanceCannotBeNegativeZero {
            get {
                return ResourceManager.GetString("MsgDistanceCannotBeNegativeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance is not a valid number.
        /// </summary>
        internal static string MsgDistanceNotValidNumber {
            get {
                return ResourceManager.GetString("MsgDistanceNotValidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East Bound Longitude must be floating point number.
        /// </summary>
        internal static string MsgEBLMustBeFloat {
            get {
                return ResourceManager.GetString("MsgEBLMustBeFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East Bound Longitude not a valid number.
        /// </summary>
        internal static string MsgEBLNotValidNum {
            get {
                return ResourceManager.GetString("MsgEBLNotValidNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in GeoExtend module. Check if geo_extend binary file has execute permisions..
        /// </summary>
        internal static string MsgErrorGeoExtendModule {
            get {
                return ResourceManager.GetString("MsgErrorGeoExtendModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in a East Bound Longitude.
        /// </summary>
        internal static string MsgFillEBLong {
            get {
                return ResourceManager.GetString("MsgFillEBLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in an e-mail address.
        /// </summary>
        internal static string MsgFillEmail {
            get {
                return ResourceManager.GetString("MsgFillEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in an e-mail address.
        /// </summary>
        internal static string MsgFillEmailAddress {
            get {
                return ResourceManager.GetString("MsgFillEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in a Code.
        /// </summary>
        internal static string MsgFillInCode {
            get {
                return ResourceManager.GetString("MsgFillInCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in a keyword.
        /// </summary>
        internal static string MsgFillInKeyword {
            get {
                return ResourceManager.GetString("MsgFillInKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in a vocabulary name.
        /// </summary>
        internal static string MsgFillInVocabulary {
            get {
                return ResourceManager.GetString("MsgFillInVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in a North Bound Latitude.
        /// </summary>
        internal static string MsgFillNBLat {
            get {
                return ResourceManager.GetString("MsgFillNBLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in an Organisation Name.
        /// </summary>
        internal static string MsgFillOrgName {
            get {
                return ResourceManager.GetString("MsgFillOrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in a South Bound Latitude.
        /// </summary>
        internal static string MsgFillSBLat {
            get {
                return ResourceManager.GetString("MsgFillSBLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in an address (URL).
        /// </summary>
        internal static string MsgFillUrl {
            get {
                return ResourceManager.GetString("MsgFillUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in a West Bound Longitude.
        /// </summary>
        internal static string MsgFillWBLong {
            get {
                return ResourceManager.GetString("MsgFillWBLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a free text limitation constraint.
        /// </summary>
        internal static string MsgFreeTextLimitConst {
            get {
                return ResourceManager.GetString("MsgFreeTextLimitConst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date more recent than To date..
        /// </summary>
        internal static string MsgFromDateMoreRecentThanDate {
            get {
                return ResourceManager.GetString("MsgFromDateMoreRecentThanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic Extend not found.
        /// </summary>
        internal static string MsgGeogrExtendNotFound {
            get {
                return ResourceManager.GetString("MsgGeogrExtendNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Data Theme already exists.
        /// </summary>
        internal static string MsgInspireThemeExists {
            get {
                return ResourceManager.GetString("MsgInspireThemeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address not valid.
        /// </summary>
        internal static string MsgInvalidEmail {
            get {
                return ResourceManager.GetString("MsgInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid URL.
        /// </summary>
        internal static string MsgInvalidUrl {
            get {
                return ResourceManager.GetString("MsgInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword already exists.
        /// </summary>
        internal static string MsgKeywordExists {
            get {
                return ResourceManager.GetString("MsgKeywordExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords not found.
        /// </summary>
        internal static string MsgKeywordsNotFound {
            get {
                return ResourceManager.GetString("MsgKeywordsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitations on public access not found.
        /// </summary>
        internal static string MsgLimitPublicAccessNotFound {
            get {
                return ResourceManager.GetString("MsgLimitPublicAccessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineage free text not found.
        /// </summary>
        internal static string MsgLineageFreeTextNotFound {
            get {
                return ResourceManager.GetString("MsgLineageFreeTextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address already exists.
        /// </summary>
        internal static string MsgMailExists {
            get {
                return ResourceManager.GetString("MsgMailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata XML saved!.
        /// </summary>
        internal static string MsgMetadataXMLSaved {
            get {
                return ResourceManager.GetString("MsgMetadataXMLSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Language not found.
        /// </summary>
        internal static string MsgMetaLangNotFound {
            get {
                return ResourceManager.GetString("MsgMetaLangNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Bound Latitude must be floating point number.
        /// </summary>
        internal static string MsgNBLMustBeFloat {
            get {
                return ResourceManager.GetString("MsgNBLMustBeFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Bound Latitude not a valid number.
        /// </summary>
        internal static string MsgNBLNotValidNum {
            get {
                return ResourceManager.GetString("MsgNBLNotValidNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of Contact metadata not found.
        /// </summary>
        internal static string MsgNoPointOfContact {
            get {
                return ResourceManager.GetString("MsgNoPointOfContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid Geographic Extend found.
        /// </summary>
        internal static string MsgNoValidGeogrExtFound {
            get {
                return ResourceManager.GetString("MsgNoValidGeogrExtFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization info already exists.
        /// </summary>
        internal static string MsgOrgExists {
            get {
                return ResourceManager.GetString("MsgOrgExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Language already exists.
        /// </summary>
        internal static string MsgResourceLangExists {
            get {
                return ResourceManager.GetString("MsgResourceLangExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Language metadata not found.
        /// </summary>
        internal static string MsgResourceLangMetaNotFound {
            get {
                return ResourceManager.GetString("MsgResourceLangMetaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Abstract metadata not found.
        /// </summary>
        internal static string MsgResourceMetaNotFound {
            get {
                return ResourceManager.GetString("MsgResourceMetaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Title metadata not found.
        /// </summary>
        internal static string MsgResourceTitleMetaNotFound {
            get {
                return ResourceManager.GetString("MsgResourceTitleMetaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Type not selected.
        /// </summary>
        internal static string MsgResourceTypeNotSelected {
            get {
                return ResourceManager.GetString("MsgResourceTypeNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible Party metadata not found.
        /// </summary>
        internal static string MsgRespPartMetaNotFound {
            get {
                return ResourceManager.GetString("MsgRespPartMetaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Bound Latitude is larger than North Bound Latitude..
        /// </summary>
        internal static string MsgSBLLargerThanNBL {
            get {
                return ResourceManager.GetString("MsgSBLLargerThanNBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Bound Latitude must be floating point number.
        /// </summary>
        internal static string MsgSBLMustBeFloat {
            get {
                return ResourceManager.GetString("MsgSBLMustBeFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Bound Latitude not a valid number.
        /// </summary>
        internal static string MsgSBLNotValidNum {
            get {
                return ResourceManager.GetString("MsgSBLNotValidNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale already exists.
        /// </summary>
        internal static string MsgScaleAlreadyExists {
            get {
                return ResourceManager.GetString("MsgScaleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale cannot be negative or zero.
        /// </summary>
        internal static string MsgScaleCannotBeNegativeZero {
            get {
                return ResourceManager.GetString("MsgScaleCannotBeNegativeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale is not a valid integer.
        /// </summary>
        internal static string MsgScaleNotValidInteger {
            get {
                return ResourceManager.GetString("MsgScaleNotValidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a contact to remove.
        /// </summary>
        internal static string MsgSelContactToRemove {
            get {
                return ResourceManager.GetString("MsgSelContactToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a title.
        /// </summary>
        internal static string MsgSelectATitle {
            get {
                return ResourceManager.GetString("MsgSelectATitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a conformance degree.
        /// </summary>
        internal static string MsgSelectConformanceDegree {
            get {
                return ResourceManager.GetString("MsgSelectConformanceDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a conformance record to remove.
        /// </summary>
        internal static string MsgSelectConfRecordToRemove {
            get {
                return ResourceManager.GetString("MsgSelectConfRecordToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a date type.
        /// </summary>
        internal static string MsgSelectDateType {
            get {
                return ResourceManager.GetString("MsgSelectDateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an extend to remove.
        /// </summary>
        internal static string MsgSelectExtendToRemove {
            get {
                return ResourceManager.GetString("MsgSelectExtendToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a limitation constraint.
        /// </summary>
        internal static string MsgSelectLimitConst {
            get {
                return ResourceManager.GetString("MsgSelectLimitConst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an organisation record to remove.
        /// </summary>
        internal static string MsgSelectOrgRecordRemove {
            get {
                return ResourceManager.GetString("MsgSelectOrgRecordRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a publication date to remove.
        /// </summary>
        internal static string MsgSelectPublicationDateToRemove {
            get {
                return ResourceManager.GetString("MsgSelectPublicationDateToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a quality record to remove.
        /// </summary>
        internal static string MsgSelectRecordToRemove {
            get {
                return ResourceManager.GetString("MsgSelectRecordToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a temporal extend to remove.
        /// </summary>
        internal static string MsgSelectTemporalExtendToRemove {
            get {
                return ResourceManager.GetString("MsgSelectTemporalExtendToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select valid distance.
        /// </summary>
        internal static string MsgSelectValidDistance {
            get {
                return ResourceManager.GetString("MsgSelectValidDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select valid scale.
        /// </summary>
        internal static string MsgSelectValidScale {
            get {
                return ResourceManager.GetString("MsgSelectValidScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select valid units.
        /// </summary>
        internal static string MsgSelectValidUnits {
            get {
                return ResourceManager.GetString("MsgSelectValidUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Inspire Data Theme.
        /// </summary>
        internal static string MsgSelInspireTheme {
            get {
                return ResourceManager.GetString("MsgSelInspireTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item to remove.
        /// </summary>
        internal static string MsgSelItemToRemove {
            get {
                return ResourceManager.GetString("MsgSelItemToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an e-mail to remove.
        /// </summary>
        internal static string MsgSelMailToRemove {
            get {
                return ResourceManager.GetString("MsgSelMailToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a record to remove.
        /// </summary>
        internal static string MsgSelRecToRemove {
            get {
                return ResourceManager.GetString("MsgSelRecToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a reference date type.
        /// </summary>
        internal static string MsgSelRefDateType {
            get {
                return ResourceManager.GetString("MsgSelRefDateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Resource Language.
        /// </summary>
        internal static string MsgSelResourceLang {
            get {
                return ResourceManager.GetString("MsgSelResourceLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Resource Language to remove.
        /// </summary>
        internal static string MsgSelResourceLangToRemove {
            get {
                return ResourceManager.GetString("MsgSelResourceLangToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Topic Category.
        /// </summary>
        internal static string MsgSelTopicCategory {
            get {
                return ResourceManager.GetString("MsgSelTopicCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Topic Category to remove.
        /// </summary>
        internal static string MsgSelTopicCategoryToRemove {
            get {
                return ResourceManager.GetString("MsgSelTopicCategoryToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Temporal Reference must be completed.
        /// </summary>
        internal static string MsgTempRefMustBeCompleted {
            get {
                return ResourceManager.GetString("MsgTempRefMustBeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Category not found.
        /// </summary>
        internal static string MsgTopicCategNotFound {
            get {
                return ResourceManager.GetString("MsgTopicCategNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This topic category is already selected.
        /// </summary>
        internal static string MsgTopicCatSelected {
            get {
                return ResourceManager.GetString("MsgTopicCatSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Resource Identifier not found.
        /// </summary>
        internal static string MsgUniqueResourceIdNotFound {
            get {
                return ResourceManager.GetString("MsgUniqueResourceIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web address (URL) exists in the list.
        /// </summary>
        internal static string MsgUrlExists {
            get {
                return ResourceManager.GetString("MsgUrlExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! A creation date for the same title already exists..
        /// </summary>
        internal static string MsgWarningCreationDateAlreadyExists {
            get {
                return ResourceManager.GetString("MsgWarningCreationDateAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! This publication date already exists..
        /// </summary>
        internal static string MsgWarningPublDateExists {
            get {
                return ResourceManager.GetString("MsgWarningPublDateExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! This publication date already exists for this title.
        /// </summary>
        internal static string MsgWarningPublDateExistsForTitle {
            get {
                return ResourceManager.GetString("MsgWarningPublDateExistsForTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! This record already exists..
        /// </summary>
        internal static string MsgWarningRecordExists {
            get {
                return ResourceManager.GetString("MsgWarningRecordExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Bound Longitude is larger than East Bound Longitude..
        /// </summary>
        internal static string MsgWBLLargerThanEBL {
            get {
                return ResourceManager.GetString("MsgWBLLargerThanEBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Bound Longitude must be floating point number.
        /// </summary>
        internal static string MsgWBLMustBeFloat {
            get {
                return ResourceManager.GetString("MsgWBLMustBeFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Bound Longitude not a valid number.
        /// </summary>
        internal static string MsgWBLNotValidNum {
            get {
                return ResourceManager.GetString("MsgWBLNotValidNum", resourceCulture);
            }
        }
    }
}
