//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIMED {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GIMED.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code already exists.
        /// </summary>
        internal static string MsgCodeExists {
            get {
                return ResourceManager.GetString("MsgCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in a East Bound Longitude.
        /// </summary>
        internal static string MsgFillEBLong {
            get {
                return ResourceManager.GetString("MsgFillEBLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in an e-mail address.
        /// </summary>
        internal static string MsgFillEmail {
            get {
                return ResourceManager.GetString("MsgFillEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in an e-mail address.
        /// </summary>
        internal static string MsgFillEmailAddress {
            get {
                return ResourceManager.GetString("MsgFillEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in a Code.
        /// </summary>
        internal static string MsgFillInCode {
            get {
                return ResourceManager.GetString("MsgFillInCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in a keyword.
        /// </summary>
        internal static string MsgFillInKeyword {
            get {
                return ResourceManager.GetString("MsgFillInKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in a vocabulary name.
        /// </summary>
        internal static string MsgFillInVocabulary {
            get {
                return ResourceManager.GetString("MsgFillInVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in a North Bound Latitude.
        /// </summary>
        internal static string MsgFillNBLat {
            get {
                return ResourceManager.GetString("MsgFillNBLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in an Organisation Name.
        /// </summary>
        internal static string MsgFillOrgName {
            get {
                return ResourceManager.GetString("MsgFillOrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in a South Bound Latitude.
        /// </summary>
        internal static string MsgFillSBLat {
            get {
                return ResourceManager.GetString("MsgFillSBLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in an address (URL).
        /// </summary>
        internal static string MsgFillUrl {
            get {
                return ResourceManager.GetString("MsgFillUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in a West Bound Longitude.
        /// </summary>
        internal static string MsgFillWBLong {
            get {
                return ResourceManager.GetString("MsgFillWBLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Data Theme already exists.
        /// </summary>
        internal static string MsgInspireThemeExists {
            get {
                return ResourceManager.GetString("MsgInspireThemeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address not valid.
        /// </summary>
        internal static string MsgInvalidEmail {
            get {
                return ResourceManager.GetString("MsgInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid URL.
        /// </summary>
        internal static string MsgInvalidUrl {
            get {
                return ResourceManager.GetString("MsgInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword already exists.
        /// </summary>
        internal static string MsgKeywordExists {
            get {
                return ResourceManager.GetString("MsgKeywordExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address already exists.
        /// </summary>
        internal static string MsgMailExists {
            get {
                return ResourceManager.GetString("MsgMailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization info already exists.
        /// </summary>
        internal static string MsgOrgExists {
            get {
                return ResourceManager.GetString("MsgOrgExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Language already exists.
        /// </summary>
        internal static string MsgResourceLangExists {
            get {
                return ResourceManager.GetString("MsgResourceLangExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a contact to remove.
        /// </summary>
        internal static string MsgSelContactToRemove {
            get {
                return ResourceManager.GetString("MsgSelContactToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Inspire Data Theme.
        /// </summary>
        internal static string MsgSelInspireTheme {
            get {
                return ResourceManager.GetString("MsgSelInspireTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item to remove.
        /// </summary>
        internal static string MsgSelItemToRemove {
            get {
                return ResourceManager.GetString("MsgSelItemToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an e-mail to remove.
        /// </summary>
        internal static string MsgSelMailToRemove {
            get {
                return ResourceManager.GetString("MsgSelMailToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a record to remove.
        /// </summary>
        internal static string MsgSelRecToRemove {
            get {
                return ResourceManager.GetString("MsgSelRecToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a reference date type.
        /// </summary>
        internal static string MsgSelRefDateType {
            get {
                return ResourceManager.GetString("MsgSelRefDateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Resource Language.
        /// </summary>
        internal static string MsgSelResourceLang {
            get {
                return ResourceManager.GetString("MsgSelResourceLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Topic Category.
        /// </summary>
        internal static string MsgSelTopicCategory {
            get {
                return ResourceManager.GetString("MsgSelTopicCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Topic Category to remove.
        /// </summary>
        internal static string MsgSelTopicCategoryToRemove {
            get {
                return ResourceManager.GetString("MsgSelTopicCategoryToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This topic category is already selected.
        /// </summary>
        internal static string MsgTopicCatSelected {
            get {
                return ResourceManager.GetString("MsgTopicCatSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL already exists.
        /// </summary>
        internal static string MsgUrlExists {
            get {
                return ResourceManager.GetString("MsgUrlExists", resourceCulture);
            }
        }
    }
}
